# Generated by Django 5.0.4 on 2024-04-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsPlanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='items',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
