# Generated by Django 5.0.4 on 2024-04-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsPlanner', '0002_event_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='items',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='items',
            field=models.TextField(max_length=200),
        ),
    ]
