# Generated by Django 5.0.4 on 2024-04-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsPlanner', '0003_alter_event_items_alter_rsvp_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='additionalPeople',
            field=models.TextField(max_length=200),
        ),
    ]
